export const ADD_TODO = "ADD_TODO"
export const IMPORT_TODOS = "IMPORT_TODOS"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const CLEAR_COMPLETED = "CLEAR_COMPLETED"
export const SET_FILTER = "SET_FILTER"
